### ISSUE TITLE
關鍵字搜尋，沒有打完整書名就不行&再次搜尋

### ISSUE THREAD

**Issue by Ariel1206** [Shiun0413/SA_Book-Sharing#11]
1.關鍵字搜尋，沒有打完整書名就不行
2.顯示搜尋結果的頁面是否要也有搜尋功能，不然每次要在搜尋還要點回首頁。
3.旁邊menu的搜尋欄要新增搜尋功能?
![bug2](https://user-images.githubusercontent.com/105278732/170819899-edc0fe60-59c9-4b3f-8a30-97a291178452.gif)

**Comment by pinyu01** [comment]
index_bar.html fixed
第三點左側搜尋欄已修正
