### ISSUE TITLE
書籍一覽.php -->「擁有」改為放使用者拍攝的封面; 上架書籍.php-->分享者可以設定別人借走後可以借幾天，可以上傳書況圖，原本要打書籍介紹文改成打備註; broken.php-->放書況圖，刪除不必要內容

### ISSUE THREAD

**Issue by pinyu01** [Shiun0413/SA_Book-Sharing#80]

**Comment by Ariel1206** [comment]
![image](https://user-images.githubusercontent.com/105278732/173109060-f47a289f-2555-4d60-ab24-859d5b5ee17a.png)
![image](https://user-images.githubusercontent.com/105278732/173109089-25901e8f-15d6-4249-bdd6-a1c839d5282e.png)
![image](https://user-images.githubusercontent.com/105278732/173109110-410c1f3c-845e-44a8-b7fb-130e310dcaf7.png)

**Comment by Shiun0413** [comment]
# 刪除線表示已完成

書籍一覽.php --> ~~「擁有」改為放使用者拍攝的封面;~~ 
上架書籍.php--> ~~分享者可以設定別人借走後可以借幾天~~，可以上傳書況圖，原本要打書籍介紹文改成打備註; 
broken.php-->放書況圖，刪除不必要內容

@pinyu01 @Ariel1206 @sam650095 @Alvin59567

**Comment by Shiun0413** [comment]
Duplicate of #65
