### ISSUE TITLE
首頁的書籍ISBN要改掉，目前全部都是一樣的

### ISSUE THREAD

**Issue by Ariel1206** [Shiun0413/SA_Book-Sharing#83]
![bug1](https://user-images.githubusercontent.com/105278732/173178007-fe021a37-835a-4299-a617-2dfb1f900199.gif)

**Comment by pinyu01** [comment]
![ISBN_fixed](https://user-images.githubusercontent.com/104435602/173208474-bbf06e46-c1ef-4ceb-a4bb-eac56844e02b.gif)
